<?php
/**
 * @file
 * islandora_related_content.module
 */

error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

// Access Callbacks
module_load_include('inc', 'islandora_related_content', 'includes/access_callbacks');

// Query
module_load_include('inc', 'islandora_related_content', 'includes/query_helper_functions.form');

// Forms
module_load_include('inc', 'islandora_related_content', 'forms/rc.form');

/**
 * Implements hook_menu()
 *
 * @return mixed
 */
function islandora_related_content_menu() {
  /** # Related Content Page
   *
   * Shows a Related Content form for each type of content related to this object.
   */
  $urls['islandora/object/%islandora_object/related_content'] = array(
    'title' => 'Related Content',
    'page callback' => 'islandora_related_content_page_callback',
    'page arguments' => array(2),
    'access callback' => 'islandora_related_content_page_access',
    'access arguments' => array(2),
    'type' => MENU_LOCAL_TASK,
    'file' => 'page_callbacks/related_content.page_callback.inc'
  );

  /** # Ingest new a new Object */
  $urls['islandora/object/%islandora_object/related_content/ingest/%islandora_cmodel'] = array(
    'title callback' => 'islandora_cmodel_action_title',
    'title arguments' => array('Ingest', 5),
    'page callback' => 'islandora_related_content_ingest_page_callback',
    'page arguments' => array(2, 5),
    'access callback' => 'islandora_object_access',
    'access arguments' => array(ISLANDORA_INGEST, 2),
    'type' => MENU_CALLBACK,
    'file' => 'page_callbacks/ingest.page_callback.inc'

  );

  return $urls;
}

