<?php

module_load_include('inc', 'islandora_related_content', 'forms/form_elements/content_table_select');
module_load_include('inc', 'islandora_related_content', 'forms/form_elements/fedora_relationship_select');
module_load_include('inc', 'islandora_related_content', 'forms/form_elements/ingest_add_element');
module_load_include('inc', 'islandora_related_content', 'forms/form_elements/solr_filter');
module_load_include('inc', 'islandora_related_content', 'forms/form_elements/solr_filter_field_select');
